apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-inference-service
  namespace: llm
  labels:
    app: llm-inference-service
    version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llm-inference-service
  template:
    metadata:
      labels:
        app: llm-inference-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: llm-api
          image: satishpolireddy/llm-inference-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: BACKEND
              value: "hf"
            - name: MODEL_NAME
              value: "meta-llama/Llama-3.2-1B-Instruct"
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            - name: CACHE_TTL
              value: "3600"
            - name: CACHE_SIMILARITY_THRESHOLD
              value: "0.92"
            - name: LOG_LEVEL
              value: "INFO"
            - name: WORKERS
              value: "4"
          resources:
            requests:
              cpu: "2"
              memory: "8Gi"
            limits:
              cpu: "4"
              memory: "16Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: model-cache
              mountPath: /root/.cache/huggingface
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: model-cache-pvc
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: llm
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          command: ["redis-server", "--appendonly", "yes"]
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data-pvc
